version: '2.28.1'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgressql
      POSTGRES_DB: user_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DB_USER: admin
      DB_PASSWORD: postgressql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: user_data
    ports:
      - "1000:1000"
    depends_on:
      - postgres

volumes:
  postgres_data:
